redis:
    address: 172.16.23.239:6379
    dbNum: 0  #only in singleton and sentinel
    password: 
    enable: true
    model: singleton  #sentinel
    pool:
       maxIdle: 10
       maxTotal: 200
       maxWaitMillis: 3000
       minIdle: 1
       testOnCreate: true
       testOnReturn: true
       connectionTimeout: 3000
       soTimeout: 3000
    sentinel: 
       masterName: 
    cluster:
       maxAttempts: 10  
           
server_port: 8080

zookeeper:
  #服务端会在sessionTimeout时间向客户端发送心跳包如果因为一些问题没有响应ack给到服务端，且时间超过了sessionTimeout则表示会话超时了
  sessionTimeout: 2000
  address: 172.16.23.239:2181
  
   
