redis:
    address: 
    dbNum: 0
    password: 
    password: fulihui.com
    enable: true
    model: singleton
    pool:
       maxIdle: 10
       maxTotal: 200
       maxWaitMillis: 
       minIdle: 
       testOnCreate: 
       testOnReturn: 
       connectionTimeout: 
       soTimeout: 
    sentinel: 
       masterName: 
    cluster:
       maxAttempts:   
           
server_port: 8080

zookeeper:
  nodeName: testnode
  service:
    timeout: 300
    url: 192.168.1.41:2181,192.168.1.45:2181,192.168.1.46:2181

