redis:
    address: 172.16.8.183:6379
    dbNum: 0
    password: husixu
    enable: true
    model: singleton
    pool:
       maxIdle: 10
       maxTotal: 200
       maxWaitMillis: 3000
       minIdle: 1
       testOnCreate: true
       testOnReturn: true
       connectionTimeout: 3000
       soTimeout: 3000
    sentinel: 
       masterName: 
    cluster:
       maxAttempts:   
           
server_port: 8080

zookeeper:
  nodeName: testnode
  service:
    timeout: 300
    url: 192.168.1.41:2181,192.168.1.45:2181,192.168.1.46:2181

